<?php

return [
    'defaults' => [
        'min_chars' => 2,
        'limit' => 12,
        'static_field_weights' => [
            'title' => 100,
            'keywords' => 80,
            'group' => 45,
            'badge' => 35,
            'summary' => 30,
        ],
    ],

    'scopes' => [
        'admin' => [
            'min_chars' => 2,
            'limit' => 12,

            'groups' => [
                'demo' => [
                    'label_key' => 'ui.demo',
                    'icon' => 'fa-solid fa-chart-line',
                    'order' => 10,
                ],
                'helpers' => [
                    'label_key' => 'ui.helpers',
                    'icon' => 'fa-solid fa-table-cells-large',
                    'order' => 20,
                ],
                'modules' => [
                    'label_key' => 'ui.modules',
                    'icon' => 'fa-solid fa-boxes-stacked',
                    'order' => 30,
                ],
                'settings' => [
                    'label_key' => 'ui.settings',
                    'icon' => 'fa-solid fa-wrench',
                    'order' => 40,
                ],
                'account' => [
                    'label_key' => 'ui.account',
                    'icon' => 'fa-solid fa-user',
                    'order' => 50,
                ],
            ],

            'statics' => [
                'dashboard' => [
                    'title_key' => 'ui.dashboard',
                    'summary_key' => 'components/search-engine.admin.dashboard.summary',
                    'group' => 'demo',
                    'badge_key' => 'ui.demo',
                    'icon' => 'fa-solid fa-chart-line',
                    'route' => 'dashboard',
                    'keywords_key' => 'components/search-engine.admin.dashboard.keywords',
                    'weight' => 100,
                ],
                'helpers' => [
                    'title_key' => 'components/search-engine.admin.helpers.title',
                    'summary_key' => 'components/search-engine.admin.helpers.summary',
                    'group' => 'helpers',
                    'badge_key' => 'ui.summary',
                    'icon' => 'fa-solid fa-table-cells-large',
                    'route' => 'helpers.index',
                    'keywords_key' => 'components/search-engine.admin.helpers.keywords',
                    'weight' => 95,
                ],
                'modules' => [
                    'title_key' => 'components/search-engine.admin.modules.title',
                    'summary_key' => 'components/search-engine.admin.modules.summary',
                    'group' => 'modules',
                    'badge_key' => 'ui.summary',
                    'icon' => 'fa-solid fa-boxes-stacked',
                    'route' => 'modules.index',
                    'keywords_key' => 'components/search-engine.admin.modules.keywords',
                    'weight' => 95,
                ],
                'image-preview' => [
                    'title' => 'ImagePreview',
                    'summary_key' => 'components/search-engine.admin.image-preview.summary',
                    'group' => 'modules',
                    'badge_key' => 'ui.modules',
                    'icon' => 'fa-regular fa-images',
                    'route' => 'modules.show',
                    'route_parameters' => ['module' => 'image-preview'],
                    'keywords_key' => 'components/search-engine.admin.image-preview.keywords',
                    'weight' => 85,
                ],
                'visits' => [
                    'title' => 'Visits',
                    'summary_key' => 'components/search-engine.admin.visits.summary',
                    'group' => 'modules',
                    'badge_key' => 'ui.modules',
                    'icon' => 'fa-solid fa-chart-line',
                    'route' => 'modules.show',
                    'route_parameters' => ['module' => 'visits'],
                    'keywords_key' => 'components/search-engine.admin.visits.keywords',
                    'weight' => 85,
                ],
                'notifications-ui' => [
                    'title' => 'Notifications UI',
                    'summary_key' => 'components/search-engine.admin.notifications-ui.summary',
                    'group' => 'modules',
                    'badge_key' => 'ui.modules',
                    'icon' => 'fa-regular fa-bell',
                    'route' => 'modules.show',
                    'route_parameters' => ['module' => 'notifications-ui'],
                    'keywords_key' => 'components/search-engine.admin.notifications-ui.keywords',
                    'weight' => 85,
                ],
                'maintenance-mode' => [
                    'title_key' => 'ui.maintenance',
                    'summary_key' => 'components/search-engine.admin.maintenance-mode.summary',
                    'group' => 'settings',
                    'badge_key' => 'ui.settings',
                    'icon' => 'fa-solid fa-wrench',
                    'route' => 'configs.maintenance',
                    'keywords_key' => 'components/search-engine.admin.maintenance-mode.keywords',
                    'weight' => 100,
                ],
                'site-preview' => [
                    'title_key' => 'ui.site_preview',
                    'summary_key' => 'components/search-engine.admin.site-preview.summary',
                    'group' => 'settings',
                    'badge_key' => 'ui.demo',
                    'icon' => 'fa-solid fa-globe',
                    'route' => 'web.preview',
                    'keywords_key' => 'components/search-engine.admin.site-preview.keywords',
                    'weight' => 70,
                ],
                'profile' => [
                    'title_key' => 'ui.my_profile',
                    'summary_key' => 'components/search-engine.admin.profile.summary',
                    'group' => 'account',
                    'badge_key' => 'ui.account',
                    'icon' => 'fa-solid fa-user',
                    'route' => 'account.my-profile',
                    'keywords_key' => 'components/search-engine.admin.profile.keywords',
                    'weight' => 80,
                ],
                'account-notifications' => [
                    'title_key' => 'ui.notifications',
                    'summary_key' => 'components/search-engine.admin.account-notifications.summary',
                    'group' => 'account',
                    'badge_key' => 'ui.account',
                    'icon' => 'fa-regular fa-bell',
                    'route' => 'account.notifications',
                    'keywords_key' => 'components/search-engine.admin.account-notifications.keywords',
                    'weight' => 75,
                ],
                'security' => [
                    'title_key' => 'ui.security',
                    'summary_key' => 'components/search-engine.admin.security.summary',
                    'group' => 'account',
                    'badge_key' => 'ui.account',
                    'icon' => 'fa-solid fa-fingerprint',
                    'route' => 'account.security',
                    'keywords_key' => 'components/search-engine.admin.security.keywords',
                    'weight' => 75,
                ],
            ],
        ],
    ],
];
